---
abstract: 'Generate random sets of Czech names.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  List::MoreUtils: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mock-Person-CZ
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Exporter: 0
  Readonly: 0
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Mock-Person-CZ
  homepage: https://github.com/tupinek/Mock-Person-CZ
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: git://github.com/tupinek/Mock-Person-CZ
version: 0.03
