---
abstract: 'Generate random sets of Czech names.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  List::MoreUtils: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mock-Person-CZ
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Exporter: 0
  Readonly: 0
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Mock-Person-CZ
  homepage: https://github.com/tupinek/Mock-Person-CZ
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Mock-Person-CZ
version: '0.05'
